# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-25 19:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200326_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 19, 9, 18, 294431, tzinfo=utc)),
        ),
    ]
