# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-26 06:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200326_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 6, 30, 45, 333968, tzinfo=utc)),
        ),
    ]
